### PR TITLE
Css canvas medical

### PR DESCRIPTION
**Pull request by jdfenlason**
Screen Shot 2021-03-14 at 8 58 14 PM
Screen Shot 2021-03-14 at 8 58 04 PM

sorry for the sloppy css I was going to go back through it but then time and stuff... bleh

### CODE REVIEW

**Comment by jdfenlason** [comment]
Screen Shot 2021-03-15 at 11 30 12 AM
Screen Shot 2021-03-15 at 11 30 26 AM
Had some time this morning and fixed a couple of things.  Couldn't get the overlay to work however and it is probably too dark as well.

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Hey Jared!! This is already looking way better than your first screenshot, nice job! One thing I still see that needs fixing: your buttons are misaligned in the sections they are in, make sure they are centered and level with the content in the same way as in the example. As to your issue with the overlay, there are a few different ways to approach it, but feel free to reach out if you have questions!

**Comment by codingcodymiller** [comment]
LMAO *Jacob

**Comment by jdfenlason** [comment]
Screen Shot 2021-03-16 at 10 09 44 AM
Screen Shot 2021-03-16 at 10 10 06 AM

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Hey dude!! A few more visual fixes for you to better match the example:

1. Your gradient for the hero image looks like it is laying on top of the text for the hero image, make sure the overlay is behind the text.
2. Your buttons are too small as compared to the example
3. The text in your footers is too bunched up as compared to the text from the example. You should also try to add some space around the text.
4. The canvas logo in the header and footer is too large as compared to the example.
5. The "ready to learn more?" section should have the text indented slightly, rather than resting against the edge of the container.

Get these items fixed up and push up your updates, and I will take a closer look!

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Hey dude! Please attach updated screenshots after your last round of fixes

**Comment by jdfenlason** [comment]
Screen Shot 2021-03-18 at 9 58 51 AM
Screen Shot 2021-03-18 at 9 59 03 AM

**Review by codingcodymiller — APPROVED** [review]
Nice work on this, dude!!

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
One piece of feedback, actually. It looks like maybe some of the C SS you are setting aren't actually going to have an effect on the output. You should open this in the browser and uncheck each piece of styling individually, and see what properties if any are not doing anything. If they aren't doing anything, please remove them, and resubmit with the properties that have no effect removed. If they all turn out to be necessary and make changes, let me know, and I can approve this 😁

**Review by codingcodymiller — APPROVED** [review]
Awesome work!!

**Pull request merged**
